### ISSUE TITLE
Updating pin fails due to dirty repo

### ISSUE THREAD

**Issue by Seb-MCaw** [mosteo/aaa#7]
We have observed some issues when updating branch pins on this crate. Should the `config/aaa_config.*` files be `.gitignore`ed?

To reproduce:
- `alr init xxx`
- `cd xxx`
- `alr pin aaa --use=https://github.com/mosteo/aaa --branch=master`
- `alr build`
- Edit the pin in `alire.toml`, changing `branch='master'` to `branch='feat/machine-output'`
- `alr update`
- Observe
  ```
  error: Your local changes to the following files would be overwritten by checkout:
        config/aaa_config.ads
        config/aaa_config.gpr
        config/aaa_config.h
  Please commit your changes or stash them before you switch branches.
  ```

**Comment by mosteo** [comment]
Actually I prefer to have `config/` checked in, so the project can be theoretically built outside of Alire and there is no "hidden" code.

But this should certainly work, so it must be addressed in Alire itself.
